- name: install MariaDB Server
  yum: name=mariadb-server state=present
  register: installed_mariadb

- name: start mariadb Server
  service: name=mariadb state=started enabled=yes
  register: started_mariadb
  when: installed_mariadb|succeeded

#- name: Create root user password
#  command: mysqladmin -u root password '{{ mariadb_root_password }}'
#  when: started_mariadb|succeeded

- name: Change root user password
  mysql_user:
    name: root
    host: localhost
    password: '{{ mariadb_root_password }}'
  when: started_mariadb|succeeded

- name: install .my.cnf
  template:
    src: templates/my.cnf
    dest: /root/.my.cnf
    owner: root
    mode: 0600

- name: remove anonymous user
  mysql_user: login_user=root login_password='{{ mariadb_root_password }}' name='' host=localhost state=absent

