- name: install git 
  yum: name=git state=present


- name: check cloned weko
  stat: path=/root/repository
  register: is_weko

- name: checkout weko
  command: git clone https://bitbucket.org/niijp/weko.git repository chdir=/root
  register: checkedout_weko
  when:
    - is_weko.stat.exists==False

- name: copy weko
  command: cp -rp /root/repository /var/www/html/nc2/webapp/modules/
  when:
    - checkedout_weko is succeeded
    - is_weko.stat.exists==False

- name: chown weko
  command: chown -R apache:apache /var/www/html/nc2/webapp/modules/repository
  when:
    - checkedout_weko is succeeded
    - is_weko.stat.exists==False


- name: check installed weko
  stat: path=/var/www/html/nc2/webapp/modules/repository
  register: installed_weko

- name: chown weko
  file: path=/var/www/html/nc2/webapp/modules/repository owner=apache group=apache
  when:
    - installed_weko.stat.exists==True
