- name: install php
  yum: name=php state=present

- name: install php package
  yum: 
    name:
      - php-cli
      - php-pear
      - php-common
      - php-gd
      - php-mbstring
      - php-pdo
      - php-mysql
    state: present

- name: install php.ini
  template:
    src: templates/php.ini
    dest: /etc/php.ini
    owner: root
    mode: 0644
  notify: restart httpd
