- name: install base packages
  apt:
    name: "{{ packages }}"
  vars:
    packages:
      - python3-dev
      - libssl-dev
      - gcc
  become: true

- name: install pip
  apt:
    name: "{{ packages }}"
  vars:
    packages:
      - pip
  become: true

- name: update pip 
  pip:
    name: 
      - pip
    state: latest
  become: true

- name: install pip package 
  pip:
    name: 
      - docker
      - docker-compose
    state: latest
  become: true

