- name: Update repositories cache
  become: yes
  apt: update_cache=yes

- name: Install build-essential
  become: yes
  apt: name=build-essential state=present

- name: Install the libselinux-python package
  become: yes
  apt: name=python3-selinux state=present

-

