Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-20.04"
  config.vm.network "private_network", ip: "192.168.10.20", virtualbox__intnet: "intnet"
     #config.vm.hostname = "weko3.example.org"
  config.disksize.size = "200GB"

  module OS
    def OS.windows?
      Vagrant::Util::Platform.windows?
    end
  
    def OS.mac?
      (/darwin/ =~ Vagrant::Util::Platform.platform) != nil
    end
  
    def OS.unix?
      !Vagrant::Util::Platform.platform
    end
  
    def OS.linux?
      OS.unix? and not OS.mac?
    end
  end


  $install_script = <<-SHELL_SCRIPT
    echo "net.bridge.bridge-nf-call-iptables=1"|sudo tee -a /etc/sysctl.conf
    sudo sysctl net.bridge.bridge-nf-call-iptables=1
    echo "vm.max_map_count = 262144"|sudo tee -a /etc/sysctl.conf
    sudo sysctl vm.max_map_count=262144
    sudo apt-get -allow update
    sudo apt-get install -y apt-transport-https ca-certificates curl gnupg-agent software-properties-common
    curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
    sudo add-apt-repository -y "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
    sudo add-apt-repository -y ppa:git-core/ppa
    sudo apt-get -y update
    sudo apt-get install -y docker-ce docker-ce-cli containerd.io git
    sudo usermod -aG docker vagrant && newgrp docker
    sudo systemctl start docker
    sudo systemctl enable docker
    sudo curl -s -L "https://github.com/docker/compose/releases/download/v2.12.0/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
    sudo chmod +x /usr/local/bin/docker-compose
    sudo ln -s /usr/local/bin/docker-compose /usr/bin/docker-compose
    sudo apt-get install -y glusterfs-client conntrack
    sudo curl -s -L "https://storage.googleapis.com/kubernetes-release/release/v1.21.1/bin/linux/amd64/kubectl" -o /usr/local/bin/kubectl
    sudo curl -s -L "https://storage.googleapis.com/minikube/releases/latest/minikube_latest_amd64.deb" -o /tmp/minikube_latest_amd64.deb
    sudo dpkg -i /tmp/minikube_latest_amd64.deb
    curl -s -L "https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3" -o get_helm.sh
    bash get_helm.sh
    SHELL_SCRIPT

  config.vm.synced_folder ".", "/vagrant", type: "virtualbox"

  if Vagrant.has_plugin?("vagrant-vbguest")
    # set auto_update to false, if you do NOT want to check the correct
    config.vbguest.auto_update = true
  end

  #config.vm.network "forwarded_port", guest: 80, host: 8080, host_ip: "127.0.0.1"
  #config.vm.network "forwarded_port", guest: 443, host: 8443, host_ip: "127.0.0.1"  
  config.vm.network "forwarded_port", guest: 22, host: 2223 , id: "ssh"

  
  config.vm.provider "virtualbox" do |vb|
    vb.memory = 16384
    vb.cpus = 4
  end

  if OS.windows?
    config.vm.provision "shell", inline: $install_script
  else
    config.vm.provision "ansible" do |ansible|
      ansible.playbook = "../minikube.yml"
      ansible.inventory_path = "hosts"
      ansible.limit = 'all'
      ansible.host_key_checking = false
    end
  end
end
