- name: add docker-ce repository
  get_url:
    url: https://download.docker.com/linux/centos/docker-ce.repo
    dest: /etc/yum.repos.d/docer-ce.repo
  become: yes

- name: install docker-ce
  package:
    name: docker-ce
    state: latest
  become: yes

- name: start docker service
  service:
    name: docker
    state: started
    enabled: yes
  become: yes

- name: add user vagrant to docker group
  user:
    name: vagrant
    groups: docker
    append: yes
  become: yes