- name: configure vm.max_map_count
  sysctl:
    name: vm.max_map_count
    value: '262144'
    state: present
  become: true

- name: Reboot the machine (Wait for 5 min)
  become: true    
  reboot:
    reboot_timeout: 300
