- name: directory check
  stat:
    path: /home/vagrant/weko
  register: d

- name: check out WEKO3
  when: not d.stat.exists
  git:
    repo: 'https://github.com/RCOSDP/weko.git'
    dest: /home/vagrant/weko
    version: master 
  register: gitclone

#- debug: var=gitclone

- name: check WEKO3 build
  shell: |
    docker images weko* | grep -v REPOSITORY |awk '{print $1}'|sort|xargs 
  args:
    chdir: /home/vagrant/weko
  register: weko3_build_check

#- debug: var=weko3_build_check

- name: start WEKO3 build
  when: gitclone.changed or weko3_build_check.stdout!="weko_elasticsearch weko_nginx weko_web"  
  shell: |
    docker-compose build
  args:
    chdir: /home/vagrant/weko
  register: weko3_built
  until: not weko3_built.failed
  retries: 3
  delay: 60

# - debug: var=weko3_built

- name: check WEKO3 containers
  shell: |
    docker-compose ps --services --filter "status=running" | sort|xargs 
  args:
    chdir: /home/vagrant/weko
  register: weko3_containers_check

#- debug: var=weko3_containers_check

- name: start WEKO3 service 
  when: weko3_built.changed or weko3_containers_check.stdout!="elasticsearch flower nginx postgresql rabbitmq redis web" 
  shell: |
    docker-compose up -d
  args:
    chdir: /home/vagrant/weko
  register: weko3_started

# - debug: var=weko3_started

- name: Wait 300 seconds for port 443
  wait_for:
    port: 443
    delay: 30
    host: 127.0.0.1
  register: weko3_port_check
  until: not weko3_port_check.failed
  retries: 10
  delay: 3

- name: check WEKO3 service
  uri:
    url: https://127.0.0.1/ping
    method: GET
    return_content: no
    validate_certs: no
    status_code: [502, 200]
  register: weko3_api_result
  until: not weko3_api_result.failed
  retries: 10
  delay: 3

# - debug: var=weko3_api_result

- name: init WEKO3
  when: weko3_api_result.status == 502
  shell: |
    docker-compose exec web ./scripts/populate-instance.sh
    docker cp scripts/demo/item_type.sql $(docker-compose ps -q postgresql):/tmp/
    docker-compose exec postgresql psql -U invenio invenio  -f /tmp/item_type.sql
    docker-compose exec web invenio workflow init action_status,Action
  args:
    chdir: /home/vagrant/weko
  register: init_weko3

#- debug: var=init_weko3  


